### ISSUE TITLE
Declare license?

### ISSUE THREAD

**Issue by Freso** [huberf/lastfm-scrobbler#1]
There’s no license declared anywhere that I can find; no `LICENSE` or `COPYING`, no mention in the README, no comment blurb at the top of code files, no designation in `setup.py`. That means that this is currently proprietary “source‐available” software and shouldn’t be used in open source projects. I assume this is not what was intended? Maybe specify a license to make the intentions clear? :)

**Comment by huberf** [comment]
Apologies for the oversight. I've added a license now under the MIT license format. The project is definitely meant to be completely open and free to modify and use. Thanks!
